services:
  # questdb:
  #   image: questdb/questdb
  #   container_name: fintacharts-questdb
  #   ports:
  #     - "9000:9000" # web console
  #     - "9009:9009" # InfluxDB line protocol
  #     - "9009:9009" # PostgreSQL wire protocol
  #   volumes:
  #     - ./questdb_data:/root/.questdb
  #   environment:
  #     - QDB_CAIRO_SQL_COPY_BUFFER_SIZE=2097152
  #   networks:
  #     - finta_network

  backend:
    build:
      context: ./backend-dotnet
      dockerfile: Dockerfile
    container_name: finta-backend-dotnet
    ports:
      - "5000:5000"
    # depends_on:
    #   - questdb
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    env_file:
      - .env
    networks:
      - finta_network

  frontend:
    build:
      context: ./frontend-solid
      dockerfile: Dockerfile
    container_name: finta-frotnend-solid
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - finta_network

# volumes:
#   questdb_data:

networks:
  finta_network:
    driver: bridge
