services:
  timescaledb:
    build:
      context: ./timescaledb
      dockerfile: Dockerfile
    container_name: finta-timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: AssetMarket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - finta_network

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: finta-backend-dotnet
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - timescaledb
    networks:
      - finta_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: finta-frotnend-solid
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
      - VITE_WS_URL=ws://localhost:5000/ws
    depends_on:
      - backend
    networkds:
      - finta_network

volumes:
  pg_data:

networks:
  finta_network:
    driver: bridge
